#!/usr/bin/env python3
"""Writes the single-question probes into edge/: one file per question, so that asm6x's
verdict on each (accepted, warned, refused) is its own, and ASM6x's can be set beside it.
  python3 gen-edges.py            writes edge/NNN-name.s
"""
import os

here = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(here, 'edge')
os.makedirs(out, exist_ok=True)

def ins(*lines):
    """an instruction probe: the lines in .text between a back label and a forward one, ext .ref'd"""
    return '\t.ref ext\n\t.text\nback:\n' + ''.join('\t' + l + '\n' for l in lines) + 'fwd:\n\tNOP\n'

def raw(text):
    return text if text.endswith('\n') else text + '\n'

cases = [
    # constants and their ranges
    ('mvk-65535', ins('MVK 65535, A0')),
    ('mvk-32768', ins('MVK 32768, A0')),
    ('mvk-m32769', ins('MVK -32769, A0')),
    ('mvk-0xffff', ins('MVK 0xFFFF, A0')),
    ('mvk-symbol', ins('MVK ext, A0')),
    ('mvk-label', ins('MVK fwd, A0')),
    ('mvkl-33bit', ins('MVKL 0x123456789, A0')),
    ('mvkl-m1', ins('MVKL -1, A0', 'MVKH -1, A0')),
    ('mvkh-65535', ins('MVKH 65535, A0')),
    ('mvklh-big', ins('MVKLH 0x12345678, A0')),
    ('mvk-pair', ins('MVK 5, A1:A0')),
    ('addk-32768', ins('ADDK 32768, A0')),
    ('addk-m32768', ins('ADDK -32768, A0')),
    ('nop-0', ins('NOP 0')),
    ('nop-10', ins('NOP 10')),
    ('nop-pred', ins('[A0] NOP')),
    ('nop-pred-3', ins('[A0] NOP 3')),
    ('and-reg-cst', ins('AND A1, 5, A2')),
    ('or-reg-cst', ins('OR A1, 5, A2')),
    ('xor-reg-cst', ins('XOR A1, 5, A2')),
    ('and-cst-m16', ins('AND -16, A1, A2')),
    ('and-cst-m17', ins('AND -17, A1, A2')),
    ('and-cst-16', ins('AND 16, A1, A2')),
    ('and-cst-cross', ins('AND 3, B1, A2')),
    ('mpy-cst-first', ins('MPY 5, A1, A2')),
    ('mpy-cst-second', ins('MPY A1, 5, A2')),
    ('mpy-cst-neg', ins('MPY -16, A1, A2')),
    ('mpyu-cst', ins('MPYU 5, A1, A2')),
    ('mpy32-cst', ins('MPY32 5, A1, A2')),
    ('lmbd-cst', ins('LMBD 1, A1, A2')),
    ('cmpgtu-16', ins('CMPGTU 16, A1, A2')),
    ('cmpgtu-31', ins('CMPGTU 31, A1, A2')),
    ('cmpltu-31', ins('CMPLTU 31, A1, A2')),
    ('cmpltu-32', ins('CMPLTU 32, A1, A2')),
    ('cmpgtu-reg-20', ins('CMPGTU A1, 20, A2')),
    ('cmpeq-16', ins('CMPEQ 16, A1, A2')),
    ('cmpeq-reg-cst-cross', ins('CMPEQ B1, 3, A2')),
    ('cmpeq-cst-cross', ins('CMPEQ 3, B1, A2')),
    ('cmplt-cst-cross', ins('CMPLT 3, B1, A2')),
    ('sub-cst-first-16', ins('SUB 16, A1, A2')),
    ('sub-cst-first-m16', ins('SUB -16, A1, A2')),
    ('sub-cst-first-m17', ins('SUB -17, A1, A2')),
    ('sub-cst-first-cross', ins('SUB 3, B1, A2')),
    ('add-cst-first-neg', ins('ADD -3, A1, A2')),
    ('add-cst-first-31', ins('ADD 31, A1, A2')),
    ('add-cst-first-32', ins('ADD 32, A1, A2')),
    ('add-cst-first-m17', ins('ADD -17, A1, A2')),
    ('add-cst-first-cross', ins('ADD 3, B1, A2')),
    ('add-reg-cst-32', ins('ADD A1, 32, A2')),
    ('sub-reg-cst-32', ins('SUB A1, 32, A2')),
    ('add-reg-cst-m17', ins('ADD A1, -17, A2')),
    ('sub-reg-cst-m17', ins('SUB A1, -17, A2')),
    ('sub-reg-cst-m32', ins('SUB A1, -32, A2')),
    ('add-reg-cst-cross', ins('ADD B1, 3, A2')),
    ('add-reg-cst-m4-cross', ins('ADD B1, -4, A2')),
    ('sub-reg-cst-cross', ins('SUB B1, 3, A2')),
    ('shl-cross-cst', ins('SHL B1, 3, A2')),
    ('shr-cross-cst', ins('SHR B1, 3, A2')),
    ('shru-cross-cst', ins('SHRU B1, 3, A2')),
    ('shl-count-cross', ins('SHL A1, B2, A3')),
    ('shl-32', ins('SHL A1, 32, A2')),
    ('ext-cross', ins('EXT B1, 3, 7, A2')),
    ('ext-32', ins('EXT A1, 32, 7, A2')),
    ('addaw-cross', ins('ADDAW B1, A2, A3')),
    ('addaw-cst-cross', ins('ADDAW B1, 2, A3')),
    ('addaw-b15-big', ins('ADDAW B15, 100, B3')),
    ('addab-b14-big', ins('ADDAB B14, 1000, B3')),
    ('addah-b15-32767', ins('ADDAH B15, 32767, B3')),
    ('addaw-b15-32768', ins('ADDAW B15, 32768, B3')),
    ('addaw-a4-32', ins('ADDAW A4, 32, A3')),
    ('addu-cst', ins('ADDU 5, A1, A5:A4')),
    ('addu-pair-src', ins('ADDU A1:A0, A2, A5:A4')),
    ('add-pair-src', ins('ADD A1:A0, A2, A5:A4')),
    ('add-pair-cross', ins('ADD B1, A2, A5:A4')),
    ('sub-pair-cross', ins('SUB B1, A2, A5:A4')),
    ('mpy32u-reg-dst', ins('MPY32U A1, A2, A3')),
    ('mpy32-pair-dst', ins('MPY32 A1, A2, A5:A4')),
    ('mv-pair-cross', ins('MV A5:A4, B5:B4')),
    ('mv-cst', ins('MV 5, A0')),
    ('zero-pred', ins('[A0] ZERO A1')),
    ('zero-pair-b', ins('ZERO B5:B4')),
    ('not-pair', ins('NOT A5:A4, A7:A6')),
    ('neg-cross', ins('NEG B1, A2')),
    ('norm-pair', ins('NORM A5:A4, A2')),
    ('abs-cross', ins('ABS B1, A2')),
    ('mvc-a-out', ins('MVC CSR, A1')),
    ('mvc-pred', ins('[B0] MVC B1, CSR')),
    ('mvc-cross-out', ins('MVC A1, CSR')),
    ('mvc-unknown', ins('MVC B1, FOO')),
    ('swe-pred', ins('[A0] SWE')),
    ('idle-pred', ins('[A0] IDLE')),
    # branches
    ('b-cst', ins('B 0x100')),
    ('b-ext-addend', ins('B ext+8')),
    ('b-fwd-addend', ins('B fwd+4')),
    ('b-back-neg', ins('NOP', 'B back-4')),
    ('bnop-ext-addend', ins('BNOP ext+4, 2')),
    ('bnop-fwd-addend', ins('BNOP fwd+4, 2')),
    ('bnop-nocount', ins('BNOP fwd')),
    ('bnop-6', ins('BNOP fwd, 6')),
    ('callp-ext-addend', ins('CALLP ext+4, A3')),
    ('callp-b4', ins('CALLP ext, B4')),
    ('callp-pred', ins('[A0] CALLP ext, A3')),
    ('b-pred-both', ins('[!B0] B fwd', '[B2] B ext', '[!A2] B A3')),
    ('b-weak-same-section', raw('\t.weak w\n\t.text\nback:\n\tB w\nw:\n\tNOP\n')),
    ('b-global-same-section', raw('\t.global g\n\t.text\nback:\n\tB g\ng:\n\tNOP\n')),
    ('b-other-code-section', raw('\t.text\nback:\n\tB other\n\t.sect ".text:f"\nother:\n\tNOP\n')),
    ('b-data-label', raw('\t.data\nd:\t.word 1\n\t.text\nback:\n\tB d\n')),
    ('b-set-alias', raw('\t.text\nback:\n\tB al\nfwd:\n\tNOP\nal\t.set fwd\n')),
    ('b-reach-max', raw('\t.text\n\tNOP\n\tB fwd\n\t.space 0x3FFFF4\nfwd:\n\tNOP\n')),
    ('b-reach-over', raw('\t.text\n\tNOP\n\tB fwd\n\t.space 0x3FFFF8\nfwd:\n\tNOP\n')),
    ('b-reach-back-max', raw('\t.text\nfwd:\n\tNOP\n\t.space 0x3FFFFC\n\tB fwd\n')),
    ('b-reach-back-over', raw('\t.text\nfwd:\n\tNOP\n\t.space 0x400000\n\tB fwd\n')),
    ('bnop-reach-max', raw('\t.text\n\tBNOP fwd, 0\n\t.space 0x7F8\nfwd:\n\tNOP\n')),
    ('bnop-reach-over', raw('\t.text\n\tBNOP fwd, 0\n\t.space 0x7FC\nfwd:\n\tNOP\n')),
    # registers and spelling
    ('lowercase-regs', ins('mv a0, b1')),
    ('lowercase-pred', ins('[a0] mv A0, B1')),
    ('lowercase-mnemonic', ins('mv A0, B1')),
    ('lowercase-directive', raw('\t.TEXT\n\tNOP\n\t.Word 1\n')),
    ('reg-a32', ins('MV A32, A1')),
    ('unit-named', ins('ADD .L1 A1, A2, A3')),
    ('pair-odd', ins('STDW A4:A5, *A1')),
    ('pair-cross-sides', ins('STDW A5:B4, *A1')),
    # memory operands
    ('mem-no-sign', ins('LDW *A4(4), A5')),
    ('mem-no-sign-bracket', ins('LDW *A4[1], A5')),
    ('mem-bracket', ins('LDW *+A4[1], A5', 'LDW *-A4[2], A5', 'LDB *+A4[3], A5', 'LDDW *+A4[31], A5:A4')),
    ('mem-unaligned', ins('LDW *+A4(3), A5')),
    ('mem-neg-15bit', ins('LDW *-B15(128), A2')),
    ('mem-lddw-15bit', ins('LDDW *+B15(256), A5:A4')),
    ('mem-ldb-b14-32767', ins('LDB *+B14(32767), A2')),
    ('mem-ldb-b14-32768', ins('LDB *+B14(32768), A2')),
    ('mem-ldw-b15-131068', ins('LDW *+B15(131068), A2')),
    ('mem-ldw-b15-131072', ins('LDW *+B15(131072), A2')),
    ('mem-ldw-a4-128', ins('LDW *+A4(128), A2')),
    ('mem-neg-offset', ins('LDW *+B15(-4), A2')),
    ('mem-post-nocount', ins('LDW *B15++, A2', 'LDB *A4--, A5', 'LDDW *++A4, A5:A4')),
    ('mem-post-bracket', ins('LDW *B15++[2], A2', 'LDW *--A4[3], A5')),
    ('mem-plus-noparen', ins('LDW *+B15, A2')),
    ('mem-15bit-post', ins('LDW *B15++(128), A2')),
    ('mem-15bit-bracket', ins('LDW *+B15[32], A2')),
    ('mem-b14-store-h', ins('STH A2, *+B14(2000)', 'STB A2, *+B14(2000)', 'LDHU *+B14(2000), A2', 'LDBU *+B14(2000), A2')),
    ('mem-15bit-pred', ins('[A1] LDW *+B15(128), A2')),
    ('mem-15bit-cross', ins('LDW *+B15(128), B2', 'STW B2, *+B14(128)')),
    ('mem-ldw-into-pair', ins('LDW *A4, A5:A4')),
    ('mem-lddw-into-reg', ins('LDDW *A4, A5')),
    ('mem-fwd-constant', ins('LDW *+B15(K), A2') + 'K\t.set 8\n'),
    ('mem-offset-expr', ins('LDW *+B15(4*2+8), A2')),
    ('mem-offset-label-diff', ins('LDW *+B15(fwd-back), A2')),
    ('mem-lddw-b15-124', ins('LDDW *+B15(248), A5:A4')),
    ('mem-lddw-b15-256', ins('LDDW *+B15(256), A5:A4')),
    ('mem-a-neg-31', ins('LDW *-A4(124), A5', 'STB A2, *-A1(31)')),
    ('mem-a-neg-32', ins('LDW *-A4(128), A5')),
    ('mem-reg-offset', ins('LDW *+A4[A5], A6')),
    ('mem-b15-neg-post', ins('LDW *B15--(4), A2', 'LDW *--B15(4), A2')),
    # packets
    ('par-and-shl', ins('AND A1, A2, A3', '|| SHL A4, A5, A6')),
    ('par-add-and', ins('ADD A1, A2, A3', '|| AND A4, A5, A6')),
    ('par-and-or', ins('AND A1, A2, A3', '|| OR A4, A5, A6')),
    ('par-sub-cross-shl', ins('SUB B1, A2, A3', '|| SHL A4, A5, A6')),
    ('par-sub-cross-add', ins('SUB B1, A2, A3', '|| ADD A4, A5, A6')),
    ('par-mpy32u-mpy', ins('MPY32U A1, A2, A5:A4', '|| MPY A6, A7, A8')),
    ('par-mpy32us-ldw', ins('MPY32US A1, A2, A5:A4', '|| LDW *A6, A7')),
    ('par-mpy32u-shl', ins('MPY32U A1, A2, A5:A4', '|| SHL A6, A7, A8')),
    ('par-mv-mv', ins('MV A1, A2', '|| MV A3, A4')),
    ('par-mv-ldw', ins('MV A1, A2', '|| LDW *A4, A5')),
    ('par-not-ldw', ins('NOT A1, A2', '|| LDW *A4, A5')),
    ('par-mvk-mvk', ins('MVK 5, A1', '|| MVK 100, A2')),
    ('par-mvk-cmpeq', ins('MVK 5, A1', '|| CMPEQ A2, A3, A4')),
    ('par-two-loads', ins('LDW *A4, A5', '|| LDW *A6, A7')),
    ('par-nop', ins('ADD A1, A2, A3', '|| NOP')),
    ('par-nop-first', ins('NOP', '|| ADD A1, A2, A3')),
    ('par-first', raw('\t.text\n\t|| NOP\n')),
    ('par-after-label', ins('L1: ADD A1, A2, A3', '|| ADD B1, B2, B3')),
    ('par-label-between', raw('\t.text\nback:\n\tADD A1, A2, A3\nmid:\n\t|| ADD B1, B2, B3\nfwd:\n\tNOP\n')),
    ('par-eight', ins('LDW *A4, A5', '|| LDW *B4, B5', '|| CMPEQ A1, A2, A3', '|| CMPEQ B1, B2, B3',
                      '|| SHL A6, A7, A8', '|| SHL B6, B7, B8', '|| MPY A9, A10, A11', '|| MPY B9, B10, B11')),
    ('par-across-fetch-packet', ins('NOP', 'NOP', 'NOP', 'NOP', 'NOP', 'NOP', 'NOP',
                                    'LDW *A4, A5', '|| LDW *B4, B5', '|| CMPEQ A1, A2, A3')),
    ('par-pred-pair', ins('[A0] ADD A1, A2, A3', '|| [!A0] SUB B1, B2, B3')),
    ('par-branch-branch', ins('B fwd', '|| B ext')),
    ('par-after-word', raw('\t.text\nback:\n\tADD A1, A2, A3\n\t.word 0\n\t|| ADD B1, B2, B3\n')),
    ('par-section-switch', raw('\t.text\n\tNOP\n\tNOP\n\t.sect ".text:f"\n\t.word 0, 0\n\t|| NOP\n')),
    ('par-pred-before-bar', ins('ADD A1, A2, A3', '[A0] || ADD B1, B2, B3')),
    # directives in column 1 and label shapes
    ('col1-text', raw('.text\n\tNOP\n')),
    ('col1-global', raw('.global fwd\n\t.text\nfwd:\n\tNOP\n')),
    ('col1-word', raw('\t.data\n.word 1\n')),
    ('col1-mnemonic', raw('\t.text\nNOP\n\tNOP\n')),
    ('label-space-colon', raw('\t.text\nfoo :\n\tNOP\n\tB foo\n')),
    ('label-only-lines', raw('\t.text\na:\nb:\nc:\n\tNOP\n\t.word a, b, c\n')),
    ('label-case', raw('\t.data\nFoo:\t.word 1\nfoo:\t.word 2\n\t.word Foo, foo\n')),
    ('label-dollar', raw('\t.text\n$C$L1:\n\tNOP\nL$f$x$0:\n\tNOP\n\t.word $C$L1, L$f$x$0\n')),
    ('label-mnemonic-name', raw('\t.text\nADD:\n\tNOP\n\tB ADD\n')),
    ('label-twice', raw('\t.text\na:\n\tNOP\na:\n\tNOP\n')),
    ('label-text-name', raw('\t.text\n\tNOP\n\t.word .text\n')),
    ('comment-forms', raw('* a star comment\n; a semicolon comment\n\t.text ; after a directive\n\tNOP ; after an instruction\nl1: ; after a label\n\tNOP\n')),
    ('comment-star-indented', raw('\t.text\n\t* not a comment in TI\n\tNOP\n')),
    ('end-mid-file', raw('\t.text\n\tNOP\n\t.end\n\tgarbage here\n\t.word 1\n')),
    ('empty-file', raw('')),
    ('only-comment', raw('; nothing\n')),
    ('no-trailing-newline', '\t.text\n\tNOP'),
    ('crlf', '\t.text\r\n\tNOP\r\n\t.data\r\n\t.word 1\r\n'),
    ('data-only', raw('\t.data\n\t.word 1\n')),
    ('tab-label', raw('\t.text\n\tfoo:\n\tNOP\n')),
    # .usect / .bss
    ('usect-basic', raw('x\t.usect ".far", 8, 4\n\t.text\n\tMVKL x, A0\n\tMVKH x, A0\n')),
    ('usect-noalign', raw('y\t.usect ".mybss", 3\n\t.text\n\tMVKL y, A0\n')),
    ('usect-global', raw('\t.global z\nz\t.usect ".far", 16, 8\n')),
    ('usect-twice', raw('a\t.usect ".far", 4, 4\nb\t.usect ".far", 4, 4\n\t.data\n\t.word a, b\n')),
    ('usect-no-label', raw('\t.usect ".far", 4, 4\n\t.text\n\tNOP\n')),
    ('bss-local-size', raw('\t.bss loc, 12, 4\n\t.text\n\tMVKL loc, A0\n')),
    ('bss-noalign', raw('\t.bss z, 5\n\t.bss z2, 3\n\t.data\n\t.word z, z2\n')),
    ('bss-global-after', raw('\t.bss g, 8, 8\n\t.global g\n')),
    ('bss-zero', raw('\t.bss z0, 0\n\t.global z0\n')),
    ('bss-expr', raw('\t.bss z1, 2*4, 4*2\n\t.global z1\n')),
    ('bss-fwd-size', raw('\t.bss z1, N, 4\n\t.global z1\nN\t.set 12\n')),
    ('bss-align-3', raw('\t.bss z1, 4, 3\n')),
    ('bss-in-text', raw('\t.text\n\tNOP\n\t.bss b, 4, 4\n\tNOP\n\tMVKL b, A0\n')),
    ('bss-label-before', raw('lab:\t.bss b, 4, 4\n\t.data\n\t.word lab, b\n')),
    ('sect-far-word', raw('\t.sect ".far"\n\t.word 1\n')),
    ('sect-bss-word', raw('\t.sect ".bss"\n\t.word 1\n')),
    ('word-in-bss', raw('\t.bss b, 4, 4\n\t.sect ".bss"\n\t.word 5\n')),
    # strings
    ('string-n', raw('\t.data\n\t.string "a\\nb"\n')),
    ('cstring-n', raw('\t.data\n\t.cstring "a\\nb"\n')),
    ('string-quote', raw('\t.data\n\t.string "q\\"q"\n')),
    ('string-backslash', raw('\t.data\n\t.string "\\\\"\n')),
    ('cstring-backslash', raw('\t.data\n\t.cstring "\\\\"\n')),
    ('string-hex', raw('\t.data\n\t.string "\\x41"\n')),
    ('cstring-hex', raw('\t.data\n\t.cstring "\\x41"\n')),
    ('string-octal', raw('\t.data\n\t.string "\\101"\n')),
    ('cstring-octal', raw('\t.data\n\t.cstring "\\101"\n')),
    ('string-abfv', raw('\t.data\n\t.string "\\a\\b\\f\\v"\n')),
    ('cstring-abfv', raw('\t.data\n\t.cstring "\\a\\b\\f\\v"\n')),
    ('string-tab', raw('\t.data\n\t.string "t\\tt"\n')),
    ('string-zero', raw('\t.data\n\t.string "\\0"\n')),
    ('cstring-zero', raw('\t.data\n\t.cstring "z\\0"\n')),
    ('string-numbers', raw('\t.data\n\t.string "ab", 10, 0\n')),
    ('string-number-only', raw('\t.data\n\t.string 65\n')),
    ('cstring-two', raw('\t.data\n\t.cstring "a", "b"\n')),
    ('byte-string', raw('\t.data\n\t.byte "abc"\n')),
    ('byte-string-mixed', raw('\t.data\n\t.byte "ab", 1\n')),
    ('word-string', raw('\t.data\n\t.word "a"\n')),
    ('half-string', raw('\t.data\n\t.half "ab"\n')),
    ('string-semicolon', raw('\t.data\n\t.string "a;b"\n')),
    ('string-star-col1', raw('\t.data\n\t.string "*"\n')),
    ('string-in-text', raw('\t.text\n\t.string "abc"\n\tNOP\n')),
    ('string-empty', raw('\t.data\n\t.string ""\n\t.cstring ""\n')),
    ('string-high-byte', raw('\t.data\n\t.string "\\xff\\377"\n')),
    ('char-const', raw('\t.data\n\t.byte \'a\'\n\t.word \'a\'+1\n')),
    ('char-escape', raw('\t.data\n\t.byte \'\\n\'\n')),
    ('char-quote', raw('\t.data\n\t.byte \'\'\'\'\n')),
    # numbers
    ('num-binary', raw('\t.data\n\t.word 1010b\n')),
    ('num-binary-upper', raw('\t.data\n\t.word 1010B\n')),
    ('num-hex-suffix', raw('\t.data\n\t.word 0FFh, 0ffH, 0Ah\n')),
    ('num-hex-suffix-nolead', raw('\t.data\n\t.word FFh\n')),
    ('num-octal', raw('\t.data\n\t.word 17q, 017\n')),
    ('num-0b', raw('\t.data\n\t.word 0b101\n')),
    ('num-word-33bit', raw('\t.data\n\t.word 0x100000000\n')),
    ('num-word-4294967296', raw('\t.data\n\t.word 4294967296\n')),
    ('num-word-m2147483649', raw('\t.data\n\t.word -2147483649\n')),
    ('num-word-4294967295', raw('\t.data\n\t.word 4294967295, -1, 0xFFFFFFFF\n')),
    ('num-half-65535', raw('\t.data\n\t.half 65535\n')),
    ('num-half-65536', raw('\t.data\n\t.half 65536\n')),
    ('num-half-m32769', raw('\t.data\n\t.half -32769\n')),
    ('num-byte-256', raw('\t.data\n\t.byte 256\n')),
    ('num-byte-m129', raw('\t.data\n\t.byte -129\n')),
    ('num-byte-255-m128', raw('\t.data\n\t.byte 255, -128\n')),
    ('num-float', raw('\t.data\n\t.float 1.5\n')),
    ('num-double', raw('\t.data\n\t.double 1.5\n')),
    ('num-word-decimal-big', raw('\t.data\n\t.word 99999999999999999999\n')),
    ('num-hex-big', raw('\t.data\n\t.word 0x123456789ABCDEF0123\n')),
    # expressions
    ('expr-shift', raw('\t.data\n\t.word 1<<4, 256>>2\n')),
    ('expr-and-or', raw('\t.data\n\t.word 0xFF & 0x0F, 1|2, 5^1\n')),
    ('expr-mod', raw('\t.data\n\t.word 7%3\n')),
    ('expr-not', raw('\t.data\n\t.word ~0\n')),
    ('expr-arith', raw('\t.data\n\t.word 2*3+4, (2+3)*4, -(3), 10/3, 2+3*4, 1+2-3\n')),
    ('expr-precedence-ti', raw('\t.data\n\t.word 1+2*3, 8/2*2, 8-2-2, 2*3+4*5\n')),
    ('expr-neg-div', raw('\t.data\n\t.word -7/2, 7/-2\n')),
    ('expr-div-zero', raw('\t.data\n\t.word 1/0\n')),
    ('expr-unary-plus', raw('\t.data\n\t.word +5, - -5\n')),
    ('expr-labels', raw('\t.data\nback:\t.word 1\n\t.word 2\nfwd:\t.word fwd-back, back-fwd, fwd-back+4, 4+fwd-back, (fwd-back)*2, 2*(fwd-back)\n')),
    ('expr-labels-fwd', raw('\t.data\nback:\t.word fwd-back, later-back\n\t.word 2\nfwd:\t.word 3\nlater:\t.word 4\n')),
    ('expr-ext-addend', raw('\t.ref ext\n\t.data\n\t.word ext+4, ext-4, 4+ext, ext+0x10000\n')),
    ('expr-neg-ext', raw('\t.ref ext\n\t.data\n\t.word -ext\n')),
    ('expr-two-ext', raw('\t.ref ext, ext2\n\t.data\n\t.word ext+ext2\n')),
    ('expr-two-ext-diff', raw('\t.ref ext, ext2\n\t.data\n\t.word ext-ext2\n')),
    ('expr-dollar', raw('\t.data\n\t.word $\n')),
    ('expr-dollar-text', raw('\t.text\n\tNOP\n\t.word $-4\n')),
    ('expr-cross-section-diff', raw('\t.data\nd:\t.word 1\n\t.text\nt:\n\tNOP\n\t.word t-d\n')),
    ('expr-mul-ext', raw('\t.ref ext\n\t.data\n\t.word 2*ext\n')),
    ('expr-set-arith', raw('K\t.set 2+3*4\nK2\t.set K*2\n\t.data\n\t.word K, K2, K+K2\n')),
    ('expr-set-forward', raw('\t.data\n\t.word FWD, FWD+1\nFWD\t.set 3\n')),
    ('expr-paren-missing', raw('\t.data\n\t.word (1\n')),
    ('expr-trailing-comma', raw('\t.data\n\t.byte 1,\n')),
    ('expr-empty-item', raw('\t.data\n\t.word 1,,2\n')),
    ('expr-in-mem', ins('LDW *+A4(2*2), A5')),
    ('expr-in-mvk', ins('MVK 1<<4, A0')),
    ('expr-in-add', ins('ADD A1, 2*3, A2', 'ADD 2*3, A1, A2')),
    ('expr-label-diff-in-mvk', ins('MVK fwd-back, A0', 'ADD fwd-back, A1, A2')),
    ('expr-label-in-add', ins('ADD fwd, A1, A2')),
    # .set / .equ
    ('set-forms', raw('K\t.set 5\nK2\t.equ 6\n\t.set K3, 7\n\t.equ K4, 8\nK5:\t.set 9\n\t.data\n\t.word K, K2, K3, K4, K5\n')),
    ('set-twice-same', raw('K\t.set 5\nK\t.set 5\n\t.data\n\t.word K\n')),
    ('set-twice-differ', raw('K\t.set 5\nK\t.set 6\n\t.data\n\t.word K\n')),
    ('set-of-label', raw('\t.text\nfwd:\n\tNOP\nal\t.set fwd\n\t.data\n\t.word al\n')),
    ('set-of-label-arith', raw('\t.text\nfwd:\n\tNOP\nal\t.set fwd+4\n\t.data\n\t.word al\n')),
    ('set-of-ext', raw('\t.ref ext\nal\t.set ext\n\t.data\n\t.word al\n')),
    ('set-global', raw('K\t.set 5\n\t.global K\n\t.data\n\t.word K\n')),
    ('set-negative', raw('K\t.set -1\n\t.data\n\t.word K\n\t.byte K\n\t.half K\n')),
    ('set-in-mvk', raw('K\t.set 100\n\t.text\n\tMVK K, A0\n\tMVKL K, A0\n\tMVKH K, A0\n\tADD A1, K/10, A2\n\tNOP K/50\n')),
    ('set-label-collision', raw('\t.text\nfwd:\n\tNOP\nfwd\t.set 5\n')),
    ('set-referenced-before-def-const', raw('\t.text\n\tMVK K, A0\n\tLDW *+B15(K), A1\nK\t.set 12\n')),
    ('set-of-label-diff', raw('\t.text\nback:\n\tNOP\nfwd:\n\tNOP\nL\t.set fwd-back\n\t.data\n\t.word L\n')),
    ('asg-directive', raw('\t.asg 5, K\n\t.data\n\t.word K\n')),
    # .symdepend
    ('symdepend-one-arg', raw('\t.ref dep\n\t.sect ".c6xabi.extab:f"\n\t.word 1\n\t.symdepend "dep"\n')),
    ('symdepend-unquoted', raw('\t.ref dep\n\t.sect ".c6xabi.extab:f"\n\t.word 1\n\t.symdepend dep, ".c6xabi.extab:f"\n')),
    ('symdepend-no-section', raw('\t.ref dep\n\t.text\n\tNOP\n\t.symdepend "dep", ".nosuch"\n')),
    ('symdepend-before-section', raw('\t.ref dep\n\t.symdepend "dep", ".c6xabi.extab:f"\n\t.sect ".c6xabi.extab:f"\n\t.word 1\n')),
    ('symdepend-local-sym', raw('\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.extab:f"\n\t.word 1\n\t.symdepend "f", ".c6xabi.extab:f"\n')),
    ('symdepend-twice', raw('\t.ref dep, dep2\n\t.sect ".c6xabi.extab:f"\n\t.word 1\n\t.symdepend "dep", ".c6xabi.extab:f"\n\t.symdepend "dep2", ".c6xabi.extab:f"\n\t.symdepend "dep", ".c6xabi.extab:f"\n')),
    ('symdepend-text-with-relocs', raw('\t.ref dep, ext\n\t.text\n\tMVKL ext, A0\n\tB ext\n\t.symdepend "dep", ".text"\n')),
    # .align / .space
    ('align-noarg-data', raw('\t.data\n\t.byte 1\n\t.align\n\t.byte 2\n')),
    ('align-noarg-text', raw('\t.text\n\tNOP\n\t.align\n\tNOP\n')),
    ('align-3', raw('\t.data\n\t.byte 1\n\t.align 3\n\t.byte 2\n')),
    ('align-0', raw('\t.data\n\t.byte 1\n\t.align 0\n\t.byte 2\n')),
    ('align-1', raw('\t.data\n\t.byte 1\n\t.align 1\n\t.byte 2\n')),
    ('align-64-text', raw('\t.text\n\tNOP\n\t.align 64\n\tNOP\n')),
    ('align-128-data', raw('\t.data\n\t.byte 1\n\t.align 128\n\t.byte 2\n')),
    ('align-64k', raw('\t.data\n\t.byte 1\n\t.align 65536\n\t.byte 2\n')),
    ('align-2-text', raw('\t.text\n\tNOP\n\t.byte 1\n\t.align 2\n\tNOP\n')),
    ('align-text-pad-bytes', raw('\t.text\n\tNOP\n\t.byte 1\n\t.align 8\n\tNOP\n')),
    ('align-in-bss', raw('\t.bss a, 1, 1\n\t.sect ".bss"\n\t.align 8\n\t.bss b, 1, 1\n\t.data\n\t.word a, b\n')),
    ('align-fwd-const', raw('\t.data\n\t.byte 1\n\t.align K\n\t.byte 2\nK\t.set 8\n')),
    ('space-neg', raw('\t.data\n\t.space -1\n\t.byte 1\n')),
    ('space-noarg', raw('\t.data\n\t.space\n\t.byte 1\n')),
    ('space-zero', raw('\t.data\n\t.space 0\n\t.byte 1\n')),
    ('space-in-text-3', raw('\t.text\n\tNOP\n\t.space 3\n\tNOP\n')),
    ('byte-in-text-then-nop', raw('\t.text\n\tNOP\n\t.byte 1\n\tNOP\n')),
    ('bes', raw('\t.data\nb:\t.bes 4\n\t.word b\n')),
    ('space-label', raw('\t.data\ns:\t.space 4\n\t.word s\n')),
    ('space-fwd-const', raw('\t.data\n\t.space N\nN\t.set 6\n\t.byte 1\n')),
    ('word-after-byte', raw('\t.data\n\t.byte 1\n\t.word 2\n\t.byte 3\n\t.half 4\n\t.byte 5\n\t.short 6\n')),
    ('word-in-text-after-code', raw('\t.text\n\tNOP\n\t.word fwd\n\t.byte 1\nfwd:\n\tNOP\n')),
    ('ulong-uint-uword', raw('\t.data\n\t.ulong 1\n\t.uint 2\n\t.uword 3\n\t.int 4\n\t.long 5\n\t.uhalf 6\n\t.ushort 7\n\t.ubyte 8\n\t.uchar 9\n\t.char 10\n')),
    # sections
    ('sect-foo', raw('\t.sect ".foo"\n\t.word 1\n')),
    ('sect-cinit', raw('\t.sect ".cinit"\n\t.word 1\n')),
    ('sect-fardata', raw('\t.sect ".fardata"\n\t.word 1\n')),
    ('sect-neardata-byte', raw('\t.sect ".neardata"\n\t.byte 1\n')),
    ('sect-neardata-rw', raw('\t.sect ".neardata", RW\n\t.word 1\n')),
    ('sect-neardata-ro', raw('\t.sect ".neardata", RO\n\t.word 1\n')),
    ('sect-const-byte', raw('\t.sect ".const"\n\t.byte 1\n')),
    ('sect-const-named', raw('\t.sect ".const:x"\n\t.byte 1\n\t.sect ".const:.string"\n\t.string "s"\n')),
    ('sect-data-named', raw('\t.sect ".data:x"\n\t.word 1\n')),
    ('data-byte', raw('\t.data\n\t.byte 1\n')),
    ('data-empty', raw('\t.data\n\t.text\n\tNOP\n')),
    ('sect-text-named-code', raw('\t.sect ".text:f"\nf:\n\tNOP\n\tB f\n')),
    ('sect-text-named-empty', raw('\t.sect ".text:f"\n\t.text\n\tNOP\n')),
    ('sect-text-named-data', raw('\t.sect ".text:f"\n\t.word 1\n')),
    ('sect-textfoo', raw('\t.sect ".textfoo"\n\tNOP\n')),
    ('sect-rodata', raw('\t.sect ".rodata"\n\t.byte 1\n')),
    ('sect-init-array', raw('\t.ref f\n\t.sect ".init_array"\n\t.word f\n')),
    ('sect-fini-array', raw('\t.ref f\n\t.sect ".fini_array"\n\t.word f\n')),
    ('sect-switch', raw('\t.text\nl:\n\tNOP\n\t.sect ".switch"\n\t.word l\n')),
    ('sect-extab-plain', raw('\t.sect ".c6xabi.extab"\n\t.word 1\n')),
    ('sect-exidx-plain', raw('\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.exidx"\n\t.word $EXIDX_FUNC(f), 1\n')),
    ('sect-exidx-text-named', raw('\t.sect ".text:f"\nf:\n\tNOP\n\t.sect ".c6xabi.exidx:.text:f"\n\t.word $EXIDX_FUNC(f), 1\n')),
    ('sect-exidx-before-text-named', raw('\t.sect ".c6xabi.exidx:.text:f"\n\t.word $EXIDX_FUNC(f), 1\n\t.sect ".text:f"\nf:\n\tNOP\n')),
    ('sect-exidx-no-text', raw('\t.ref f\n\t.sect ".c6xabi.exidx:.text:f"\n\t.word $EXIDX_FUNC(f), 1\n')),
    ('sect-exidx-mid-text', raw('\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.exidx:.text"\n\t.word $EXIDX_FUNC(f), 1\n\t.text\n\tNOP\n\t.sect ".c6xabi.exidx:.text"\n\t.word 2, 3\n')),
    ('sect-exidx-byte-align', raw('\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.exidx:.text"\n\t.byte 1\n')),
    ('sect-text-reopen', raw('\t.text\n\tNOP\n\t.data\n\t.word 1\n\t.text\n\tNOP\n\t.sect ".text"\n\tNOP\n')),
    ('sect-stack', raw('\t.sect ".stack"\n\t.word 1\n')),
    ('sect-sysmem', raw('\t.sect ".sysmem"\n\t.space 4\n')),
    ('sect-cio', raw('\t.sect ".cio"\n\t.word 1\n')),
    ('sect-vm6747-eh', raw('\t.sect ".vm6747.eh"\n\t.word 1\n')),
    ('sect-noarg', raw('\t.sect\n\t.word 1\n')),
    ('sect-unquoted', raw('\t.sect .foo\n\t.word 1\n')),
    ('sect-upper-text', raw('\t.sect ".TEXT"\n\tNOP\n')),
    ('sect-many', raw(''.join('\t.sect ".s%d"\n\t.word %d\n' % (i, i) for i in range(40)))),
    ('sect-exidx-align-8', raw('\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.exidx:.text"\n\t.align 8\n\t.word $EXIDX_FUNC(f), 1\n')),
    ('sect-text-align-64', raw('\t.text\n\t.align 64\n\tNOP\n')),
    ('sect-const-align-8', raw('\t.sect ".const"\n\t.align 8\n\t.word 1\n')),
    ('sect-data-align-8-first', raw('\t.data\n\t.align 8\n\t.word 1\n')),
    # symbols
    ('weak-undefined', raw('\t.weak w\n\t.data\n\t.word w\n')),
    ('weak-defined', raw('\t.weak w\n\t.data\nw:\t.word 1\n')),
    ('weak-then-global', raw('\t.weak w\n\t.global w\n\t.data\nw:\t.word 1\n')),
    ('global-then-weak', raw('\t.global w\n\t.weak w\n\t.data\nw:\t.word 1\n')),
    ('weak-bss', raw('\t.weak w\n\t.bss w, 4, 4\n')),
    ('weak-branch-other-section', raw('\t.weak w\n\t.sect ".text:w"\nw:\n\tNOP\n\t.text\n\tB w\n')),
    ('ref-then-define', raw('\t.ref f\n\t.text\nf:\n\tNOP\n')),
    ('def-undefined', raw('\t.def d\n\t.text\n\tNOP\n')),
    ('def-defined', raw('\t.def d\n\t.text\nd:\n\tNOP\n')),
    ('ref-unused', raw('\t.ref r\n\t.text\n\tNOP\n')),
    ('global-unused-undefined', raw('\t.global g\n\t.text\n\tNOP\n')),
    ('undefined-local', raw('\t.data\n\t.word nothere\n')),
    ('undefined-local-branch', raw('\t.text\n\tB nothere\n')),
    ('global-after-use', raw('\t.text\n\tB g\n\t.global g\n')),
    ('global-list', raw('\t.global a, b, c\n\t.data\na:\t.word 1\nb:\t.word 2\nc:\t.word 3\n')),
    ('global-noarg', raw('\t.global\n\t.text\n\tNOP\n')),
    ('ref-noarg', raw('\t.ref\n\t.text\n\tNOP\n')),
    ('weak-noarg', raw('\t.weak\n\t.text\n\tNOP\n')),
    ('word-noarg', raw('\t.data\n\t.word\n')),
    ('byte-noarg', raw('\t.data\n\t.byte\n')),
    ('string-noarg', raw('\t.data\n\t.string\n')),
    ('cstring-noarg', raw('\t.data\n\t.cstring\n')),
    ('set-noarg', raw('\t.set\n')),
    ('bss-noarg', raw('\t.bss\n')),
    ('usect-noarg', raw('\t.usect\n')),
    ('symdepend-noarg', raw('\t.symdepend\n')),
    ('global-number', raw('\t.global 5\n')),
    ('global-string', raw('\t.global "f"\n')),
    ('global-set-constant', raw('K\t.set 5\n\t.global K\n')),
    ('global-section-name', raw('\t.text\n\tNOP\n\t.global .text\n')),
    ('label-global-data-type', raw('\t.global d, f\n\t.data\nd:\t.word 1\n\t.text\nf:\n\tNOP\n\t.sect ".const"\n\t.global c\nc:\t.byte 1\n')),
    ('label-in-text-data', raw('\t.text\n\tNOP\ntab:\t.word 1, 2\n\t.global tab\n')),
    ('label-in-bss-sect', raw('\t.sect ".bss"\nl:\t.space 4\n\t.global l\n')),
    ('label-in-switch', raw('\t.sect ".switch"\n\t.global sw\nsw:\t.word 1\n')),
    ('label-in-exidx', raw('\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.exidx:.text"\n\t.global ex\nex:\t.word $EXIDX_FUNC(f), 1\n')),
    # relocations
    ('reloc-half-ext', raw('\t.ref ext\n\t.data\n\t.half ext\n')),
    ('reloc-byte-ext', raw('\t.ref ext\n\t.data\n\t.byte ext\n')),
    ('reloc-half-local', raw('\t.data\nl:\t.word 1\n\t.half l\n')),
    ('reloc-half-diff', raw('\t.data\nb:\t.word 1\ne:\t.half e-b, b-e\n')),
    ('reloc-word-local', raw('\t.data\nl:\t.word 1\n\t.word l, l+4, l-4\n')),
    ('reloc-word-global-local', raw('\t.global g\n\t.data\ng:\t.word 1\n\t.word g, g+4\n')),
    ('reloc-word-text-label', raw('\t.text\nf:\n\tNOP\n\t.data\n\t.word f, f+8\n')),
    ('reloc-exidx-addend', raw('\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.exidx:.text"\n\t.word $EXIDX_FUNC(f)+4\n')),
    ('reloc-extab-lp-addend', raw('\t.text\nf:\n\tNOP\nlp:\n\tNOP\n\t.sect ".c6xabi.extab:f"\n\t.word $EXTAB_LP(lp)+4, $EXTAB_LP(lp)-4\n')),
    ('reloc-scope-alone', raw('\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.extab:f"\n\t.word $EXTAB_SCOPE(f)\n')),
    ('reloc-scope-diff-word', raw('\t.text\nf:\n\tNOP\ng:\n\tNOP\n\t.sect ".c6xabi.extab:f"\n\t.word $EXTAB_SCOPE(g)-$EXTAB_SCOPE(f), $EXTAB_SCOPE(g) - $EXTAB_SCOPE(f) + 1\n\t.half $EXTAB_SCOPE(g)-$EXTAB_SCOPE(f)\n\t.byte $EXTAB_SCOPE(g)-$EXTAB_SCOPE(f)\n')),
    ('reloc-scope-cross-section', raw('\t.text\nf:\n\tNOP\n\t.sect ".text:g"\ng:\n\tNOP\n\t.sect ".c6xabi.extab:f"\n\t.word $EXTAB_SCOPE(g)-$EXTAB_SCOPE(f)\n')),
    ('reloc-rtti', raw('\t.ref _ZTIi\n\t.sect ".c6xabi.extab:f"\n\t.word $EXTAB_RTTI(_ZTIi), $EXTAB_RTTI("_ZTIi")\n')),
    ('reloc-rtti-addend', raw('\t.ref _ZTIi\n\t.sect ".c6xabi.extab:f"\n\t.word $EXTAB_RTTI(_ZTIi)+4\n')),
    ('reloc-exidx-extab-unquoted', raw('\t.ref __c6xabi_extab$f\n\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.exidx:.text"\n\t.word $EXIDX_FUNC("f"), $EXIDX_EXTAB(__c6xabi_extab$f)\n')),
    ('reloc-lowercase-operator', raw('\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.exidx:.text"\n\t.word $exidx_func(f), 1\n')),
    ('reloc-unknown-operator', raw('\t.text\nf:\n\tNOP\n\t.data\n\t.word $FOO(f)\n')),
    ('reloc-two-operators', raw('\t.text\nf:\n\tNOP\nlp:\n\tNOP\n\t.sect ".c6xabi.extab:f"\n\t.word $EXTAB_LP(lp)+$EXIDX_FUNC(f)\n')),
    ('reloc-operator-in-mvkl', ins('MVKL $EXTAB_LP(fwd), A0')),
    ('reloc-operator-in-half', raw('\t.text\nf:\n\tNOP\n\t.sect ".c6xabi.extab:f"\n\t.half $EXTAB_LP(f)\n')),
    ('reloc-mvkl-cross-diff', raw('\t.data\nd:\t.word 0\n\t.text\nback:\n\tMVKL fwd-d, A0\n\tMVKH fwd-d, A0\nfwd:\n\tNOP\n')),
    ('reloc-b-cross-diff', raw('\t.data\nd:\t.word 0\n\t.text\nback:\n\tB fwd-d\nfwd:\n\tNOP\n')),
    ('reloc-mvkl-same-diff', raw('\t.text\nback:\n\tMVKL fwd-back, A0\n\tMVKH fwd-back, A0\nfwd:\n\tNOP\n')),
    ('reloc-mvkl-set-constant', raw('K\t.set 0x12345678\n\t.text\n\tMVKL K, A0\n\tMVKH K, A0\n')),
    ('reloc-mvkl-fwd-set', raw('\t.text\n\tMVKL K, A0\n\tMVKH K, A0\nK\t.set 0x12345678\n')),
    ('reloc-mvkl-label-addend', ins('MVKL fwd+0x10000, A0', 'MVKH fwd-8, A0', 'MVKL ext+0x7FFFFFFF, A0')),
    ('reloc-word-set-plus-label', raw('K\t.set 8\n\t.text\nf:\n\tNOP\n\t.data\n\t.word f+K, K+f\n')),
    ('reloc-order', raw('\t.ref a, b, c\n\t.data\n\t.word c\n\t.text\n\tMVKL b, A0\n\tB a\n\tMVKH b, A0\n\t.word a\n\t.sect ".const"\n\t.word b\n')),
    ('reloc-weak-word', raw('\t.weak w\n\t.data\nw:\t.word 1\n\t.word w\n')),
    ('reloc-half-in-text', raw('\t.ref ext\n\t.text\n\tNOP\n\t.half ext\n')),
    ('reloc-many-symbols', raw('\t.ref ' + ', '.join('e%d' % i for i in range(300)) + '\n\t.data\n' + ''.join('\t.word e%d\n' % i for i in range(300)))),
]

names = set()
for k, (name, body) in enumerate(cases):
    assert name not in names, name
    names.add(name)
    with open(os.path.join(out, '%03d-%s.s' % (k + 1, name)), 'w', newline='') as f:
        f.write(body)
print('%d probes in %s' % (len(cases), out))
